baseURL = "http://zhangchao.xyz/"
languageCode = "zh-CN"
title = "张超的博客"
theme = "maupassant"
preserveTaxonomyNames = true
publishDir = "docs"
[author]
  name = "张超"

[params]
  author = "张超"
  keywords = "C++,Ruby,Rails,Web,算法,leetcode,编程,公众号,小程序,小游戏,英语,背单词,赚钱,财务自由,财富自由"