baseURL = "http://www.zhiwuya.fun/"
languageCode = "zh-CN"
title = "知无涯.fun"
theme = "maupassant"
## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true

hasCJKLanguage = true
summaryLength = 140

publishDir = "docs"
googleAnalytics = "UA-144916691-1"

[markup.goldmark.renderer]
  unsafe= true

[author]
  name = "张超"

[params]
  author = "张超"
  subtitle = "知识无涯，学中作乐"
  keywords = "C++,Ruby,Rails,Web,算法,leetcode,编程,公众号,小程序,小游戏,英语,背单词,赚钱,财务自由,财富自由"
  busuanzi = true #启用不算子网页统计
  # googleAd = "ca-pub-4031353640611810"  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索

## 友情链接，可以多个
[[params.links]]
  title = "单词范——最快速的背单词方法"
  name = "单词范——最快速的背单词方法"
  url = "https://www.danci.fun/"

## 侧边栏广告位
[[params.ads]]
  title = "2020上云采购季，仅￥223/3年"
  url = "https://www.aliyun.com/sale-season/2020/procurement-new-members?userCode=dgslu5jg"
  img = "https://img.alicdn.com/tfs/TB1Yr3IvubviK0jSZFNXXaApXXa-220-120.jpg"
[[params.ads]]
  title = "云服务器全场2折起"
  url = "https://www.aliyun.com/acts/limit-buy?userCode=dgslu5jg"
  img = "https://img.alicdn.com/tfs/TB1hblJl7Y2gK0jSZFgXXc5OFXa-750-400.jpg"

## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "chinazhangchao/zhangchao-comments" ##换成自己得
  issueTerm = "pathname"
  theme = "github-light"

## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

## 配置网站菜单
[menu]

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4